# Generated by Django 5.2.3 on 2025-07-01 04:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Products',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
