# Generated by Django 5.2.3 on 2025-07-08 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_alter_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='Products',
            old_name='catgeory',
            new_name='category',
        ),
    ]
