# Generated by Django 5.2.4 on 2025-08-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_catgeory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='Products',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='photos/Products'),
        ),
    ]
